services:
    web_publique: 
        image: adminprojet123/web_public:https_test
        restart: always
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/logs/nginx.log:/etc/nginx/main_access.log
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data:/var/www/certbot
        networks:
            default:
                ipv4_address: 172.16.129.4

    php:
        image: adminprojet123/php_service:latest
        networks:
            default:
                ipv4_address: 172.16.129.9

    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email he201801@students.ephec.be --agree-tos --no-eff-email -d l2-2.ephec-ti.be www.l2-2.ephec-ti.be b2b.l2-2.ephec-ti.be
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data:/var/www/certbot

    bdd:
        image: adminprojet123/bdd:latest
        networks:
            default:
                ipv4_address: 172.16.129.10

networks:
    default:
        external:
            name: zone_dmz
